django/conf/project_template/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

report/urls.py
from django.conf.urls import patterns, url
from report.views import ReportDelete

urlpatterns = patterns('report.views',
                       (r'^edit_report/(?P<rep>\d+)$', 'edit_report'),
                       url(r'delete_report/(?P<pk>\d+)$', ReportDelete.as_view(), name='del_report'),
                       (r'^new_report/$', 'add_report'),
                       (r'^meeting-reports.html$', 'main_page', {'export':'html'}),
                       (r'^meeting-reports.shtml$', 'main_page', {'export':'shtml'}),
                       (r'^$', 'main_page'),
)

urls.py
from django.conf.urls import patterns, include
from django.views.generic.base import RedirectView
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
                       (r'^timeline/', include('timeline.urls')),
                       (r'^ballot/', include('ballot.urls')),
                       (r'^project/', include('project.urls')),
                       (r'^system/', include('system.urls')),
                       (r'^report/', include('report.urls')),
                       (r'^login/$', 'django.contrib.auth.views.login'),
                       (r'^logout/$', 'django.contrib.auth.views.logout'),
                       (r'^password_change/$', 'django.contrib.auth.views.password_change'),
                       (r'^password_change/done$', 'django.contrib.auth.views.password_change_done'),
                       ('^ah/$',RedirectView.as_view(url='/_ah/admin/')),
                       ('^$', 'system.views.index_page'),
)

#urlpatterns += staticfiles_urlpatterns()

report/models.py
#############################################################################
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#############################################################################
#
#  Project Name        :    IEEE 802.11 Timeline Tool                                                                            *
#
#  Author              :    Alex Ashley
#
#############################################################################

from django.db import models
from django.utils.translation import ugettext_lazy as _

class MeetingType(object):
    def __init__(self,code,descr):
        self.code = code
        self.description = descr
        
    def __str__(self):
        return '%s'%self.description
    
    def __unicode__(self):
        return self.description
    
class MeetingReport(models.Model):
    Plenary = MeetingType('P', 'Plenary')
    Interim = MeetingType('I', 'Interim')
    Special = MeetingType('S', 'Special')
    _MEETING_TYPES = [ (b.code,b.description) for b in Plenary, Interim, Special]
    
    id = models.AutoField(primary_key=True)
    session = models.DecimalField(unique=True, db_index=True, decimal_places=1, max_digits=5, help_text=_('Session number'))
    start = models.DateField(help_text=_('Session start date'))
    end = models.DateField(help_text=_('Session end date'))
    cancelled = models.BooleanField(default=False,help_text=_(u'Session was cancelled'))
    
    pending = models.BooleanField(default=True,help_text=_(u'Reports are in-progress and will be provided later'))
    #null=True, blank=True,
    report = models.URLField(null=True, blank=True, help_text=_('URL pointing to meeting report'))
    minutes_doc = models.URLField(null=True, blank=True,
                                  help_text=_('URL pointing to meeting minutes in Word format'))
    minutes_pdf = models.URLField(null=True, blank=True,
                                  help_text=_('URL pointing to meeting minutes in PDF format'))
    
    venue = models.CharField(max_length=100, help_text=_('Name of meeting venue'))
    location = models.CharField(max_length=100, help_text=_('Location of meeting venue'))
    meeting_type = models.CharField(max_length=2, choices=_MEETING_TYPES, help_text=_('Plenary or Interim'))

    @property
    def session_num(self):
        s = int(self.session)
        return s if s==self.session else self.session
    
    def __unicode__(self):
        try:
            return '%03.1f: %s'%(int(self.session),self.location)
        except (ValueError,TypeError):
            return self.location

report/views.py
#############################################################################
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#############################################################################
#
#  Project Name        :    IEEE 802.11 Timeline Tool                                                                            *
#
#  Author              :    Alex Ashley
#
#############################################################################

from util.cache import CacheControl
from report.models import MeetingReport
from util.forms import DateModelForm
from util.io import export_html

from django.template import RequestContext
from django.shortcuts import render_to_response,  get_object_or_404
from django import http
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy

from django.contrib.auth.decorators import login_required

#@login_required
class ReportDelete(DeleteView):
    model = MeetingReport
    success_url = reverse_lazy('report.views.main_page')
    

class ReportForm(DateModelForm):
    def __init__(self, *args, **kwargs):
        super(ReportForm, self).__init__(*args, **kwargs)    

    class Meta:
        model = MeetingReport

@login_required
def main_page(request, export=None):
    context = dict(reports=MeetingReport.objects.all().order_by('-session'))
    context['export'] = export
    context['title'] = 'SUMMARY REPORTS & MINUTES OF 802.11 WG SESSIONS'
    context['next_page'] = reverse('report.views.main_page')
    context['needs_update'] = False
    context['export_page'] = 'meeting-reports' 
    context_instance=RequestContext(request)
    context_instance['cache'].export = export
    if export:
        return export_html('report/reports.html', context, context_instance=context_instance, filename='%s.%s'%(context['export_page'],export))
    return render_to_response('report/reports.html', context, context_instance=context_instance)

@login_required
def add_report(request):
    return edit_report(request,rep=None)

@login_required
def edit_report(request,rep):
    context = {}
    context.update(csrf(request))
    next_page = request.GET.get('next',reverse('report.views.main_page'))
    if rep is None:
        report = MeetingReport()
    else:
        report = get_object_or_404(MeetingReport,pk=rep)
    if request.method == 'POST':
        if request.POST.has_key('cancel'):
            return http.HttpResponseRedirect(next_page)
        if request.POST.has_key('delete'):
            return http.HttpResponseRedirect(reverse('report.views.del_report',args=[rep]))
        form = ReportForm(request.POST, request.FILES, instance=report)
        if form.is_valid():
            data = form.cleaned_data
            report = form.save()
            cc = CacheControl()
            return http.HttpResponseRedirect(next_page)
    else:
        #initial={'curstat':ballot.project.status.id, 'curpk':ballot.pk} if bal is not None else {'curstat':0}
        form = ReportForm(instance=report) #, initial=initial)
    context['form'] = form
    context['object'] = report
    context['no_delete'] = rep is None
    return render_to_response('report/edit-report.html',context, context_instance=RequestContext(request))

#@login_required
#def del_report(request,rep):
#    next_page = request.GET.get('next',reverse('report.views.main_page'))
#    return create_update.delete_object(request, model=MeetingReport, object_id=rep,
#                                       post_delete_redirect=next_page)
    

report/templates/report/edit-report.html
{% extends "edit-object.html" %}
{% block extra-head %}
<script type="text/javascript">
django.jQuery(document).ready(function() {
	var $j = django.jQuery.noConflict();
	$j("input[name='report'], input[name='minutes_doc'], , input[name='minutes_pdf']").change(function() {
		var val = $j(this).val();
		if(val){
			$j("input[name='pending']").attr('checked', false);
		}
	});
});
</script>
{% endblock %}

report/templates/report/meetingreport_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h2>Are you sure you want to delete meeting report <q>{{object}}</q>?</h2>
<form action="" method="post">
{% csrf_token %}
<input type="submit" name="confirm" value="Yes, I'm sure" />
</form>
{% endblock %}

report/templates/report/reports.html
{% extends "base.html" %}
{% load cache %}
{% load siteutils %}
{% load static %}
{% load url from future %}

{% block extra-head %}
{% if needs_update %}
<meta http-equiv="refresh" content="15">
{% endif %}
{% include_css "report.css" %}
{% endblock %}

{% block content %}
<table class="report" >
<col width="56" />
<col width="86" />
<col width="90" />
<col width="90" />
<col width="90" />
<col width="190" />
<col width="170" />
<col width="65" />
  <thead>
  <tr><th class="header" colspan="8">IEEE 802.11 WLAN WORKING GROUP SESSIONS</th></tr>
  <tr>
    <th class="notice" colspan="8">
    As our sessions are open to the public, all interested parties
      are welcome to attend IEEE P802.11 Working Group sessions, for which there
      is a registration fee, to defray the cost of the session. At Plenary
      sessions this is administered by the IEEE P802 LMSC organization. Whereas,
      the Interim sessions are normally managed by our sponsoring host. This is
      in-addition to your individual hotel accommodation, and travel expenses.
      Click here to view <a href="{{urls.example_agenda|default:'http://grouper.ieee.org/groups/802/11/Meetings/Typical_Meeting_Agenda.htm'}}">Example
      Plenary and Interim Session Agenda</a>.
      </th>
    </tr>

  <tr>
    <th rowspan="2" >Session</th>
    <th rowspan="2" >Date</th>
    <th rowspan="2">Month</th>
    <th colspan="2">File URL or Doc#</th>
    <th rowspan="2">Location</th>
    <th rowspan="2" >Place</th>
    <th rowspan="2">Type</th>
    </tr>
  <tr>
    <th >Report</th>
    <th>Minutes</th>
    </tr>
  </thead>
  <tfoot>
 <tr><td class="header" colspan="8">&nbsp;</td></tr>
 <tr><td class="notice" colspan="8">n/a Denotes - Not Applicable.</td></tr>
 <tr><td class="header" colspan="8">&nbsp;</td></tr>
 </tfoot>
  <tbody>
{% for report in reports %}
  {%ifchanged report.start.year %}
<tr>
    <td class="header" colspan="8">For Year {{report.start|date:"Y"}}</td>
    </tr>
    {%endifchanged %}
<tr class="{%cycle 'row1' 'row2' %}">
<td>
{% if not export %}<a href="{%url 'report.views.edit_report' report.pk %}?next={%url 'report.views.main_page' %}">{%endif %}
{{report.session_num}}
{% if not export %}</a>{%endif%}
</td>
<td>{{report.start|date:"j"}}<sup>{{report.start|date:"S"}}</sup> - {{report.end|date:"j"}}<sup>{{report.end|date:"S"}}</sup></td>
<td>{% ifequal report.start.month report.end.month %}{{report.start|date:"F"}}{%else%}
{{report.start|date:"M"}} / {{report.end|date:"M"}}
{%endifequal%}</td>
<td {%if report.cancelled or report.pending %}colspan="2"{%endif%}>
{%if report.cancelled %}Cancelled Session{%else%}
  {%if report.pending %}Soon to be posted{% else %}
    {%if report.report%}<a href="{{report.report}}">Report</a>{%else%}
n/a
    {%endif%}
  {%endif%}
{%endif%}
</td>
{% if not report.cancelled and not report.pending %}
<td>{%if report.minutes_doc%}<a href="{{report.minutes_doc}}">{%if report.minutes_pdf%}.doc{%else%}Minutes{%endif%}</a>{%endif%}
{%if report.minutes_pdf%}<a href="{{report.minutes_pdf}}">{%if report.minutes_doc%}.pdf{%else%}Minutes{%endif%}</a>{%endif%}
</td>{%endif%}
<td>{{report.venue}}</td>
<td>{{report.location}}</td>
<td>{{report.get_meeting_type_display}}</td>
    </tr>
 {% endfor %}
  </tbody>
</table>
{% endblock %}